services:
  db:
    image: postgres
    restart: "no"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fms-dev
  backend:
    container_name: dev-backend
    build: ./
    command: bash -c "./mvnw clean install -Dmaven.test.skip && cp target/passportService-*.jar passportService.jar && java -jar passportService.jar"
    restart: "no"
    ports:
      - 8080:8080
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fms-dev
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_PROFILES_ACTIVE=dev